import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "./providers/query-provider";
import { ModalProvider } from "./providers/modal-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ModalProvider>
          <QueryProvider>{children}</QueryProvider>
        </ModalProvider>
      </body>
    </html>
  );
}
